package com.hky.dao;

import com.hky.model.A;
import com.hky.model.AExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A
     *
     * @mbg.generated Fri Aug 18 01:49:20 CST 2017
     */
    long countByExample(AExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A
     *
     * @mbg.generated Fri Aug 18 01:49:20 CST 2017
     */
    int deleteByExample(AExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A
     *
     * @mbg.generated Fri Aug 18 01:49:20 CST 2017
     */
    int insert(A record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A
     *
     * @mbg.generated Fri Aug 18 01:49:20 CST 2017
     */
    int insertSelective(A record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A
     *
     * @mbg.generated Fri Aug 18 01:49:20 CST 2017
     */
    List<A> selectByExample(AExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A
     *
     * @mbg.generated Fri Aug 18 01:49:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") A record, @Param("example") AExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A
     *
     * @mbg.generated Fri Aug 18 01:49:20 CST 2017
     */
    int updateByExample(@Param("record") A record, @Param("example") AExample example);
}