package com.hky.wuyefeiguanli.model;

public class DealListWithBLOBs extends DealList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_LIST.ACCORD_FROM
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    private byte[] accordFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_LIST.ACCORD_TO
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    private byte[] accordTo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_LIST.ACCORD_FROM
     *
     * @return the value of DEAL_LIST.ACCORD_FROM
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public byte[] getAccordFrom() {
        return accordFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_LIST.ACCORD_FROM
     *
     * @param accordFrom the value for DEAL_LIST.ACCORD_FROM
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public void setAccordFrom(byte[] accordFrom) {
        this.accordFrom = accordFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_LIST.ACCORD_TO
     *
     * @return the value of DEAL_LIST.ACCORD_TO
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public byte[] getAccordTo() {
        return accordTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_LIST.ACCORD_TO
     *
     * @param accordTo the value for DEAL_LIST.ACCORD_TO
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public void setAccordTo(byte[] accordTo) {
        this.accordTo = accordTo;
    }
}