package com.hky.wuyefeiguanli.model;

import java.math.BigDecimal;
import java.util.Date;

public class DealList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_LIST.DEAL_ID
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    private BigDecimal dealId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_LIST.DEAL_FROM
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    private String dealFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_LIST.DEAL_TO
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    private String dealTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_LIST.MONEY
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    private BigDecimal money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_LIST.DETAIL
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_LIST.DEAL_STATE
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    private String dealState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_LIST.DEAL_CREATE_TIME
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    private Date dealCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_LIST.DEAL_FINISH_TIME
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    private Date dealFinishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_LIST.FAIL_REASON
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    private String failReason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_LIST.DEAL_ID
     *
     * @return the value of DEAL_LIST.DEAL_ID
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public BigDecimal getDealId() {
        return dealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_LIST.DEAL_ID
     *
     * @param dealId the value for DEAL_LIST.DEAL_ID
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public void setDealId(BigDecimal dealId) {
        this.dealId = dealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_LIST.DEAL_FROM
     *
     * @return the value of DEAL_LIST.DEAL_FROM
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public String getDealFrom() {
        return dealFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_LIST.DEAL_FROM
     *
     * @param dealFrom the value for DEAL_LIST.DEAL_FROM
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public void setDealFrom(String dealFrom) {
        this.dealFrom = dealFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_LIST.DEAL_TO
     *
     * @return the value of DEAL_LIST.DEAL_TO
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public String getDealTo() {
        return dealTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_LIST.DEAL_TO
     *
     * @param dealTo the value for DEAL_LIST.DEAL_TO
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public void setDealTo(String dealTo) {
        this.dealTo = dealTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_LIST.MONEY
     *
     * @return the value of DEAL_LIST.MONEY
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_LIST.MONEY
     *
     * @param money the value for DEAL_LIST.MONEY
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_LIST.DETAIL
     *
     * @return the value of DEAL_LIST.DETAIL
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_LIST.DETAIL
     *
     * @param detail the value for DEAL_LIST.DETAIL
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_LIST.DEAL_STATE
     *
     * @return the value of DEAL_LIST.DEAL_STATE
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public String getDealState() {
        return dealState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_LIST.DEAL_STATE
     *
     * @param dealState the value for DEAL_LIST.DEAL_STATE
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public void setDealState(String dealState) {
        this.dealState = dealState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_LIST.DEAL_CREATE_TIME
     *
     * @return the value of DEAL_LIST.DEAL_CREATE_TIME
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public Date getDealCreateTime() {
        return dealCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_LIST.DEAL_CREATE_TIME
     *
     * @param dealCreateTime the value for DEAL_LIST.DEAL_CREATE_TIME
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public void setDealCreateTime(Date dealCreateTime) {
        this.dealCreateTime = dealCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_LIST.DEAL_FINISH_TIME
     *
     * @return the value of DEAL_LIST.DEAL_FINISH_TIME
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public Date getDealFinishTime() {
        return dealFinishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_LIST.DEAL_FINISH_TIME
     *
     * @param dealFinishTime the value for DEAL_LIST.DEAL_FINISH_TIME
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public void setDealFinishTime(Date dealFinishTime) {
        this.dealFinishTime = dealFinishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_LIST.FAIL_REASON
     *
     * @return the value of DEAL_LIST.FAIL_REASON
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public String getFailReason() {
        return failReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_LIST.FAIL_REASON
     *
     * @param failReason the value for DEAL_LIST.FAIL_REASON
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public void setFailReason(String failReason) {
        this.failReason = failReason;
    }
}