package com.hky.wuyefeiguanli.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DealListExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public DealListExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDealIdIsNull() {
            addCriterion("DEAL_ID is null");
            return (Criteria) this;
        }

        public Criteria andDealIdIsNotNull() {
            addCriterion("DEAL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDealIdEqualTo(BigDecimal value) {
            addCriterion("DEAL_ID =", value, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdNotEqualTo(BigDecimal value) {
            addCriterion("DEAL_ID <>", value, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdGreaterThan(BigDecimal value) {
            addCriterion("DEAL_ID >", value, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DEAL_ID >=", value, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdLessThan(BigDecimal value) {
            addCriterion("DEAL_ID <", value, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DEAL_ID <=", value, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdIn(List<BigDecimal> values) {
            addCriterion("DEAL_ID in", values, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdNotIn(List<BigDecimal> values) {
            addCriterion("DEAL_ID not in", values, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DEAL_ID between", value1, value2, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DEAL_ID not between", value1, value2, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealFromIsNull() {
            addCriterion("DEAL_FROM is null");
            return (Criteria) this;
        }

        public Criteria andDealFromIsNotNull() {
            addCriterion("DEAL_FROM is not null");
            return (Criteria) this;
        }

        public Criteria andDealFromEqualTo(String value) {
            addCriterion("DEAL_FROM =", value, "dealFrom");
            return (Criteria) this;
        }

        public Criteria andDealFromNotEqualTo(String value) {
            addCriterion("DEAL_FROM <>", value, "dealFrom");
            return (Criteria) this;
        }

        public Criteria andDealFromGreaterThan(String value) {
            addCriterion("DEAL_FROM >", value, "dealFrom");
            return (Criteria) this;
        }

        public Criteria andDealFromGreaterThanOrEqualTo(String value) {
            addCriterion("DEAL_FROM >=", value, "dealFrom");
            return (Criteria) this;
        }

        public Criteria andDealFromLessThan(String value) {
            addCriterion("DEAL_FROM <", value, "dealFrom");
            return (Criteria) this;
        }

        public Criteria andDealFromLessThanOrEqualTo(String value) {
            addCriterion("DEAL_FROM <=", value, "dealFrom");
            return (Criteria) this;
        }

        public Criteria andDealFromLike(String value) {
            addCriterion("DEAL_FROM like", value, "dealFrom");
            return (Criteria) this;
        }

        public Criteria andDealFromNotLike(String value) {
            addCriterion("DEAL_FROM not like", value, "dealFrom");
            return (Criteria) this;
        }

        public Criteria andDealFromIn(List<String> values) {
            addCriterion("DEAL_FROM in", values, "dealFrom");
            return (Criteria) this;
        }

        public Criteria andDealFromNotIn(List<String> values) {
            addCriterion("DEAL_FROM not in", values, "dealFrom");
            return (Criteria) this;
        }

        public Criteria andDealFromBetween(String value1, String value2) {
            addCriterion("DEAL_FROM between", value1, value2, "dealFrom");
            return (Criteria) this;
        }

        public Criteria andDealFromNotBetween(String value1, String value2) {
            addCriterion("DEAL_FROM not between", value1, value2, "dealFrom");
            return (Criteria) this;
        }

        public Criteria andDealToIsNull() {
            addCriterion("DEAL_TO is null");
            return (Criteria) this;
        }

        public Criteria andDealToIsNotNull() {
            addCriterion("DEAL_TO is not null");
            return (Criteria) this;
        }

        public Criteria andDealToEqualTo(String value) {
            addCriterion("DEAL_TO =", value, "dealTo");
            return (Criteria) this;
        }

        public Criteria andDealToNotEqualTo(String value) {
            addCriterion("DEAL_TO <>", value, "dealTo");
            return (Criteria) this;
        }

        public Criteria andDealToGreaterThan(String value) {
            addCriterion("DEAL_TO >", value, "dealTo");
            return (Criteria) this;
        }

        public Criteria andDealToGreaterThanOrEqualTo(String value) {
            addCriterion("DEAL_TO >=", value, "dealTo");
            return (Criteria) this;
        }

        public Criteria andDealToLessThan(String value) {
            addCriterion("DEAL_TO <", value, "dealTo");
            return (Criteria) this;
        }

        public Criteria andDealToLessThanOrEqualTo(String value) {
            addCriterion("DEAL_TO <=", value, "dealTo");
            return (Criteria) this;
        }

        public Criteria andDealToLike(String value) {
            addCriterion("DEAL_TO like", value, "dealTo");
            return (Criteria) this;
        }

        public Criteria andDealToNotLike(String value) {
            addCriterion("DEAL_TO not like", value, "dealTo");
            return (Criteria) this;
        }

        public Criteria andDealToIn(List<String> values) {
            addCriterion("DEAL_TO in", values, "dealTo");
            return (Criteria) this;
        }

        public Criteria andDealToNotIn(List<String> values) {
            addCriterion("DEAL_TO not in", values, "dealTo");
            return (Criteria) this;
        }

        public Criteria andDealToBetween(String value1, String value2) {
            addCriterion("DEAL_TO between", value1, value2, "dealTo");
            return (Criteria) this;
        }

        public Criteria andDealToNotBetween(String value1, String value2) {
            addCriterion("DEAL_TO not between", value1, value2, "dealTo");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNull() {
            addCriterion("MONEY is null");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNotNull() {
            addCriterion("MONEY is not null");
            return (Criteria) this;
        }

        public Criteria andMoneyEqualTo(BigDecimal value) {
            addCriterion("MONEY =", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotEqualTo(BigDecimal value) {
            addCriterion("MONEY <>", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThan(BigDecimal value) {
            addCriterion("MONEY >", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MONEY >=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThan(BigDecimal value) {
            addCriterion("MONEY <", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MONEY <=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyIn(List<BigDecimal> values) {
            addCriterion("MONEY in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotIn(List<BigDecimal> values) {
            addCriterion("MONEY not in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MONEY between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MONEY not between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andDetailIsNull() {
            addCriterion("DETAIL is null");
            return (Criteria) this;
        }

        public Criteria andDetailIsNotNull() {
            addCriterion("DETAIL is not null");
            return (Criteria) this;
        }

        public Criteria andDetailEqualTo(String value) {
            addCriterion("DETAIL =", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotEqualTo(String value) {
            addCriterion("DETAIL <>", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailGreaterThan(String value) {
            addCriterion("DETAIL >", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailGreaterThanOrEqualTo(String value) {
            addCriterion("DETAIL >=", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailLessThan(String value) {
            addCriterion("DETAIL <", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailLessThanOrEqualTo(String value) {
            addCriterion("DETAIL <=", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailLike(String value) {
            addCriterion("DETAIL like", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotLike(String value) {
            addCriterion("DETAIL not like", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailIn(List<String> values) {
            addCriterion("DETAIL in", values, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotIn(List<String> values) {
            addCriterion("DETAIL not in", values, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailBetween(String value1, String value2) {
            addCriterion("DETAIL between", value1, value2, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotBetween(String value1, String value2) {
            addCriterion("DETAIL not between", value1, value2, "detail");
            return (Criteria) this;
        }

        public Criteria andDealStateIsNull() {
            addCriterion("DEAL_STATE is null");
            return (Criteria) this;
        }

        public Criteria andDealStateIsNotNull() {
            addCriterion("DEAL_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andDealStateEqualTo(String value) {
            addCriterion("DEAL_STATE =", value, "dealState");
            return (Criteria) this;
        }

        public Criteria andDealStateNotEqualTo(String value) {
            addCriterion("DEAL_STATE <>", value, "dealState");
            return (Criteria) this;
        }

        public Criteria andDealStateGreaterThan(String value) {
            addCriterion("DEAL_STATE >", value, "dealState");
            return (Criteria) this;
        }

        public Criteria andDealStateGreaterThanOrEqualTo(String value) {
            addCriterion("DEAL_STATE >=", value, "dealState");
            return (Criteria) this;
        }

        public Criteria andDealStateLessThan(String value) {
            addCriterion("DEAL_STATE <", value, "dealState");
            return (Criteria) this;
        }

        public Criteria andDealStateLessThanOrEqualTo(String value) {
            addCriterion("DEAL_STATE <=", value, "dealState");
            return (Criteria) this;
        }

        public Criteria andDealStateLike(String value) {
            addCriterion("DEAL_STATE like", value, "dealState");
            return (Criteria) this;
        }

        public Criteria andDealStateNotLike(String value) {
            addCriterion("DEAL_STATE not like", value, "dealState");
            return (Criteria) this;
        }

        public Criteria andDealStateIn(List<String> values) {
            addCriterion("DEAL_STATE in", values, "dealState");
            return (Criteria) this;
        }

        public Criteria andDealStateNotIn(List<String> values) {
            addCriterion("DEAL_STATE not in", values, "dealState");
            return (Criteria) this;
        }

        public Criteria andDealStateBetween(String value1, String value2) {
            addCriterion("DEAL_STATE between", value1, value2, "dealState");
            return (Criteria) this;
        }

        public Criteria andDealStateNotBetween(String value1, String value2) {
            addCriterion("DEAL_STATE not between", value1, value2, "dealState");
            return (Criteria) this;
        }

        public Criteria andDealCreateTimeIsNull() {
            addCriterion("DEAL_CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andDealCreateTimeIsNotNull() {
            addCriterion("DEAL_CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andDealCreateTimeEqualTo(Date value) {
            addCriterion("DEAL_CREATE_TIME =", value, "dealCreateTime");
            return (Criteria) this;
        }

        public Criteria andDealCreateTimeNotEqualTo(Date value) {
            addCriterion("DEAL_CREATE_TIME <>", value, "dealCreateTime");
            return (Criteria) this;
        }

        public Criteria andDealCreateTimeGreaterThan(Date value) {
            addCriterion("DEAL_CREATE_TIME >", value, "dealCreateTime");
            return (Criteria) this;
        }

        public Criteria andDealCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("DEAL_CREATE_TIME >=", value, "dealCreateTime");
            return (Criteria) this;
        }

        public Criteria andDealCreateTimeLessThan(Date value) {
            addCriterion("DEAL_CREATE_TIME <", value, "dealCreateTime");
            return (Criteria) this;
        }

        public Criteria andDealCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("DEAL_CREATE_TIME <=", value, "dealCreateTime");
            return (Criteria) this;
        }

        public Criteria andDealCreateTimeIn(List<Date> values) {
            addCriterion("DEAL_CREATE_TIME in", values, "dealCreateTime");
            return (Criteria) this;
        }

        public Criteria andDealCreateTimeNotIn(List<Date> values) {
            addCriterion("DEAL_CREATE_TIME not in", values, "dealCreateTime");
            return (Criteria) this;
        }

        public Criteria andDealCreateTimeBetween(Date value1, Date value2) {
            addCriterion("DEAL_CREATE_TIME between", value1, value2, "dealCreateTime");
            return (Criteria) this;
        }

        public Criteria andDealCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("DEAL_CREATE_TIME not between", value1, value2, "dealCreateTime");
            return (Criteria) this;
        }

        public Criteria andDealFinishTimeIsNull() {
            addCriterion("DEAL_FINISH_TIME is null");
            return (Criteria) this;
        }

        public Criteria andDealFinishTimeIsNotNull() {
            addCriterion("DEAL_FINISH_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andDealFinishTimeEqualTo(Date value) {
            addCriterion("DEAL_FINISH_TIME =", value, "dealFinishTime");
            return (Criteria) this;
        }

        public Criteria andDealFinishTimeNotEqualTo(Date value) {
            addCriterion("DEAL_FINISH_TIME <>", value, "dealFinishTime");
            return (Criteria) this;
        }

        public Criteria andDealFinishTimeGreaterThan(Date value) {
            addCriterion("DEAL_FINISH_TIME >", value, "dealFinishTime");
            return (Criteria) this;
        }

        public Criteria andDealFinishTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("DEAL_FINISH_TIME >=", value, "dealFinishTime");
            return (Criteria) this;
        }

        public Criteria andDealFinishTimeLessThan(Date value) {
            addCriterion("DEAL_FINISH_TIME <", value, "dealFinishTime");
            return (Criteria) this;
        }

        public Criteria andDealFinishTimeLessThanOrEqualTo(Date value) {
            addCriterion("DEAL_FINISH_TIME <=", value, "dealFinishTime");
            return (Criteria) this;
        }

        public Criteria andDealFinishTimeIn(List<Date> values) {
            addCriterion("DEAL_FINISH_TIME in", values, "dealFinishTime");
            return (Criteria) this;
        }

        public Criteria andDealFinishTimeNotIn(List<Date> values) {
            addCriterion("DEAL_FINISH_TIME not in", values, "dealFinishTime");
            return (Criteria) this;
        }

        public Criteria andDealFinishTimeBetween(Date value1, Date value2) {
            addCriterion("DEAL_FINISH_TIME between", value1, value2, "dealFinishTime");
            return (Criteria) this;
        }

        public Criteria andDealFinishTimeNotBetween(Date value1, Date value2) {
            addCriterion("DEAL_FINISH_TIME not between", value1, value2, "dealFinishTime");
            return (Criteria) this;
        }

        public Criteria andFailReasonIsNull() {
            addCriterion("FAIL_REASON is null");
            return (Criteria) this;
        }

        public Criteria andFailReasonIsNotNull() {
            addCriterion("FAIL_REASON is not null");
            return (Criteria) this;
        }

        public Criteria andFailReasonEqualTo(String value) {
            addCriterion("FAIL_REASON =", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonNotEqualTo(String value) {
            addCriterion("FAIL_REASON <>", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonGreaterThan(String value) {
            addCriterion("FAIL_REASON >", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonGreaterThanOrEqualTo(String value) {
            addCriterion("FAIL_REASON >=", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonLessThan(String value) {
            addCriterion("FAIL_REASON <", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonLessThanOrEqualTo(String value) {
            addCriterion("FAIL_REASON <=", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonLike(String value) {
            addCriterion("FAIL_REASON like", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonNotLike(String value) {
            addCriterion("FAIL_REASON not like", value, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonIn(List<String> values) {
            addCriterion("FAIL_REASON in", values, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonNotIn(List<String> values) {
            addCriterion("FAIL_REASON not in", values, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonBetween(String value1, String value2) {
            addCriterion("FAIL_REASON between", value1, value2, "failReason");
            return (Criteria) this;
        }

        public Criteria andFailReasonNotBetween(String value1, String value2) {
            addCriterion("FAIL_REASON not between", value1, value2, "failReason");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DEAL_LIST
     *
     * @mbg.generated do_not_delete_during_merge Sun Aug 20 20:51:56 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}