package com.hky.wuyefeiguanli.model;

import java.math.BigDecimal;
import java.util.Date;

public class HouseAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSE_ACCOUNT.DEAL_ID
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    private BigDecimal dealId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSE_ACCOUNT.HOUSE_ID
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    private BigDecimal houseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSE_ACCOUNT.DEAL_TYPE
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    private String dealType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSE_ACCOUNT.MONEY
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    private BigDecimal money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSE_ACCOUNT.DEAL_TIME
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    private Date dealTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSE_ACCOUNT.DEAL_ID
     *
     * @return the value of HOUSE_ACCOUNT.DEAL_ID
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public BigDecimal getDealId() {
        return dealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSE_ACCOUNT.DEAL_ID
     *
     * @param dealId the value for HOUSE_ACCOUNT.DEAL_ID
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public void setDealId(BigDecimal dealId) {
        this.dealId = dealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSE_ACCOUNT.HOUSE_ID
     *
     * @return the value of HOUSE_ACCOUNT.HOUSE_ID
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public BigDecimal getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSE_ACCOUNT.HOUSE_ID
     *
     * @param houseId the value for HOUSE_ACCOUNT.HOUSE_ID
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public void setHouseId(BigDecimal houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSE_ACCOUNT.DEAL_TYPE
     *
     * @return the value of HOUSE_ACCOUNT.DEAL_TYPE
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public String getDealType() {
        return dealType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSE_ACCOUNT.DEAL_TYPE
     *
     * @param dealType the value for HOUSE_ACCOUNT.DEAL_TYPE
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public void setDealType(String dealType) {
        this.dealType = dealType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSE_ACCOUNT.MONEY
     *
     * @return the value of HOUSE_ACCOUNT.MONEY
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSE_ACCOUNT.MONEY
     *
     * @param money the value for HOUSE_ACCOUNT.MONEY
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSE_ACCOUNT.DEAL_TIME
     *
     * @return the value of HOUSE_ACCOUNT.DEAL_TIME
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public Date getDealTime() {
        return dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSE_ACCOUNT.DEAL_TIME
     *
     * @param dealTime the value for HOUSE_ACCOUNT.DEAL_TIME
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public void setDealTime(Date dealTime) {
        this.dealTime = dealTime;
    }
}