package com.hky.wuyefeiguanli.model;

import java.math.BigDecimal;

public class HouseLinkman {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSE_LINKMAN.HOUSE_ID
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    private BigDecimal houseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSE_LINKMAN.NAME
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSE_LINKMAN.IDENTIFY_CARD
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    private String identifyCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSE_LINKMAN.PHONE
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSE_LINKMAN.ROLE
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSE_LINKMAN.HOUSE_ID
     *
     * @return the value of HOUSE_LINKMAN.HOUSE_ID
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public BigDecimal getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSE_LINKMAN.HOUSE_ID
     *
     * @param houseId the value for HOUSE_LINKMAN.HOUSE_ID
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public void setHouseId(BigDecimal houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSE_LINKMAN.NAME
     *
     * @return the value of HOUSE_LINKMAN.NAME
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSE_LINKMAN.NAME
     *
     * @param name the value for HOUSE_LINKMAN.NAME
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSE_LINKMAN.IDENTIFY_CARD
     *
     * @return the value of HOUSE_LINKMAN.IDENTIFY_CARD
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public String getIdentifyCard() {
        return identifyCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSE_LINKMAN.IDENTIFY_CARD
     *
     * @param identifyCard the value for HOUSE_LINKMAN.IDENTIFY_CARD
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public void setIdentifyCard(String identifyCard) {
        this.identifyCard = identifyCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSE_LINKMAN.PHONE
     *
     * @return the value of HOUSE_LINKMAN.PHONE
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSE_LINKMAN.PHONE
     *
     * @param phone the value for HOUSE_LINKMAN.PHONE
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSE_LINKMAN.ROLE
     *
     * @return the value of HOUSE_LINKMAN.ROLE
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSE_LINKMAN.ROLE
     *
     * @param role the value for HOUSE_LINKMAN.ROLE
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    public void setRole(String role) {
        this.role = role;
    }
}