package com.hky.wuyefeiguanli.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class HousePaymentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table HOUSE_PAYMENT
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table HOUSE_PAYMENT
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table HOUSE_PAYMENT
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_PAYMENT
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    public HousePaymentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_PAYMENT
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_PAYMENT
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_PAYMENT
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_PAYMENT
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_PAYMENT
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_PAYMENT
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_PAYMENT
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_PAYMENT
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_PAYMENT
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_PAYMENT
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table HOUSE_PAYMENT
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHouseIdIsNull() {
            addCriterion("HOUSE_ID is null");
            return (Criteria) this;
        }

        public Criteria andHouseIdIsNotNull() {
            addCriterion("HOUSE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andHouseIdEqualTo(BigDecimal value) {
            addCriterion("HOUSE_ID =", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotEqualTo(BigDecimal value) {
            addCriterion("HOUSE_ID <>", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdGreaterThan(BigDecimal value) {
            addCriterion("HOUSE_ID >", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("HOUSE_ID >=", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdLessThan(BigDecimal value) {
            addCriterion("HOUSE_ID <", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("HOUSE_ID <=", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdIn(List<BigDecimal> values) {
            addCriterion("HOUSE_ID in", values, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotIn(List<BigDecimal> values) {
            addCriterion("HOUSE_ID not in", values, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("HOUSE_ID between", value1, value2, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("HOUSE_ID not between", value1, value2, "houseId");
            return (Criteria) this;
        }

        public Criteria andMouthIsNull() {
            addCriterion("MOUTH is null");
            return (Criteria) this;
        }

        public Criteria andMouthIsNotNull() {
            addCriterion("MOUTH is not null");
            return (Criteria) this;
        }

        public Criteria andMouthEqualTo(String value) {
            addCriterion("MOUTH =", value, "mouth");
            return (Criteria) this;
        }

        public Criteria andMouthNotEqualTo(String value) {
            addCriterion("MOUTH <>", value, "mouth");
            return (Criteria) this;
        }

        public Criteria andMouthGreaterThan(String value) {
            addCriterion("MOUTH >", value, "mouth");
            return (Criteria) this;
        }

        public Criteria andMouthGreaterThanOrEqualTo(String value) {
            addCriterion("MOUTH >=", value, "mouth");
            return (Criteria) this;
        }

        public Criteria andMouthLessThan(String value) {
            addCriterion("MOUTH <", value, "mouth");
            return (Criteria) this;
        }

        public Criteria andMouthLessThanOrEqualTo(String value) {
            addCriterion("MOUTH <=", value, "mouth");
            return (Criteria) this;
        }

        public Criteria andMouthLike(String value) {
            addCriterion("MOUTH like", value, "mouth");
            return (Criteria) this;
        }

        public Criteria andMouthNotLike(String value) {
            addCriterion("MOUTH not like", value, "mouth");
            return (Criteria) this;
        }

        public Criteria andMouthIn(List<String> values) {
            addCriterion("MOUTH in", values, "mouth");
            return (Criteria) this;
        }

        public Criteria andMouthNotIn(List<String> values) {
            addCriterion("MOUTH not in", values, "mouth");
            return (Criteria) this;
        }

        public Criteria andMouthBetween(String value1, String value2) {
            addCriterion("MOUTH between", value1, value2, "mouth");
            return (Criteria) this;
        }

        public Criteria andMouthNotBetween(String value1, String value2) {
            addCriterion("MOUTH not between", value1, value2, "mouth");
            return (Criteria) this;
        }

        public Criteria andNeedPayIsNull() {
            addCriterion("NEED_PAY is null");
            return (Criteria) this;
        }

        public Criteria andNeedPayIsNotNull() {
            addCriterion("NEED_PAY is not null");
            return (Criteria) this;
        }

        public Criteria andNeedPayEqualTo(BigDecimal value) {
            addCriterion("NEED_PAY =", value, "needPay");
            return (Criteria) this;
        }

        public Criteria andNeedPayNotEqualTo(BigDecimal value) {
            addCriterion("NEED_PAY <>", value, "needPay");
            return (Criteria) this;
        }

        public Criteria andNeedPayGreaterThan(BigDecimal value) {
            addCriterion("NEED_PAY >", value, "needPay");
            return (Criteria) this;
        }

        public Criteria andNeedPayGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("NEED_PAY >=", value, "needPay");
            return (Criteria) this;
        }

        public Criteria andNeedPayLessThan(BigDecimal value) {
            addCriterion("NEED_PAY <", value, "needPay");
            return (Criteria) this;
        }

        public Criteria andNeedPayLessThanOrEqualTo(BigDecimal value) {
            addCriterion("NEED_PAY <=", value, "needPay");
            return (Criteria) this;
        }

        public Criteria andNeedPayIn(List<BigDecimal> values) {
            addCriterion("NEED_PAY in", values, "needPay");
            return (Criteria) this;
        }

        public Criteria andNeedPayNotIn(List<BigDecimal> values) {
            addCriterion("NEED_PAY not in", values, "needPay");
            return (Criteria) this;
        }

        public Criteria andNeedPayBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NEED_PAY between", value1, value2, "needPay");
            return (Criteria) this;
        }

        public Criteria andNeedPayNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NEED_PAY not between", value1, value2, "needPay");
            return (Criteria) this;
        }

        public Criteria andActPayIsNull() {
            addCriterion("ACT_PAY is null");
            return (Criteria) this;
        }

        public Criteria andActPayIsNotNull() {
            addCriterion("ACT_PAY is not null");
            return (Criteria) this;
        }

        public Criteria andActPayEqualTo(BigDecimal value) {
            addCriterion("ACT_PAY =", value, "actPay");
            return (Criteria) this;
        }

        public Criteria andActPayNotEqualTo(BigDecimal value) {
            addCriterion("ACT_PAY <>", value, "actPay");
            return (Criteria) this;
        }

        public Criteria andActPayGreaterThan(BigDecimal value) {
            addCriterion("ACT_PAY >", value, "actPay");
            return (Criteria) this;
        }

        public Criteria andActPayGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_PAY >=", value, "actPay");
            return (Criteria) this;
        }

        public Criteria andActPayLessThan(BigDecimal value) {
            addCriterion("ACT_PAY <", value, "actPay");
            return (Criteria) this;
        }

        public Criteria andActPayLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_PAY <=", value, "actPay");
            return (Criteria) this;
        }

        public Criteria andActPayIn(List<BigDecimal> values) {
            addCriterion("ACT_PAY in", values, "actPay");
            return (Criteria) this;
        }

        public Criteria andActPayNotIn(List<BigDecimal> values) {
            addCriterion("ACT_PAY not in", values, "actPay");
            return (Criteria) this;
        }

        public Criteria andActPayBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_PAY between", value1, value2, "actPay");
            return (Criteria) this;
        }

        public Criteria andActPayNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_PAY not between", value1, value2, "actPay");
            return (Criteria) this;
        }

        public Criteria andDealIdIsNull() {
            addCriterion("DEAL_ID is null");
            return (Criteria) this;
        }

        public Criteria andDealIdIsNotNull() {
            addCriterion("DEAL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDealIdEqualTo(BigDecimal value) {
            addCriterion("DEAL_ID =", value, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdNotEqualTo(BigDecimal value) {
            addCriterion("DEAL_ID <>", value, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdGreaterThan(BigDecimal value) {
            addCriterion("DEAL_ID >", value, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DEAL_ID >=", value, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdLessThan(BigDecimal value) {
            addCriterion("DEAL_ID <", value, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DEAL_ID <=", value, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdIn(List<BigDecimal> values) {
            addCriterion("DEAL_ID in", values, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdNotIn(List<BigDecimal> values) {
            addCriterion("DEAL_ID not in", values, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DEAL_ID between", value1, value2, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DEAL_ID not between", value1, value2, "dealId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table HOUSE_PAYMENT
     *
     * @mbg.generated do_not_delete_during_merge Sun Aug 20 20:51:55 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table HOUSE_PAYMENT
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}