package com.hky.wuyefeiguanli.model;

import java.math.BigDecimal;

public class House {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSE.HOUSE_ID
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    private BigDecimal houseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSE.VILLAGE
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    private String village;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSE.BUILDING_NO
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    private BigDecimal buildingNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSE.FLOOR_NO
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    private BigDecimal floorNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSE.ROOM_NO
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    private BigDecimal roomNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSE.FLOOR_SPACE
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    private BigDecimal floorSpace;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSE.HOUSE_ID
     *
     * @return the value of HOUSE.HOUSE_ID
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    public BigDecimal getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSE.HOUSE_ID
     *
     * @param houseId the value for HOUSE.HOUSE_ID
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    public void setHouseId(BigDecimal houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSE.VILLAGE
     *
     * @return the value of HOUSE.VILLAGE
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    public String getVillage() {
        return village;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSE.VILLAGE
     *
     * @param village the value for HOUSE.VILLAGE
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    public void setVillage(String village) {
        this.village = village;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSE.BUILDING_NO
     *
     * @return the value of HOUSE.BUILDING_NO
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    public BigDecimal getBuildingNo() {
        return buildingNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSE.BUILDING_NO
     *
     * @param buildingNo the value for HOUSE.BUILDING_NO
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    public void setBuildingNo(BigDecimal buildingNo) {
        this.buildingNo = buildingNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSE.FLOOR_NO
     *
     * @return the value of HOUSE.FLOOR_NO
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    public BigDecimal getFloorNo() {
        return floorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSE.FLOOR_NO
     *
     * @param floorNo the value for HOUSE.FLOOR_NO
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    public void setFloorNo(BigDecimal floorNo) {
        this.floorNo = floorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSE.ROOM_NO
     *
     * @return the value of HOUSE.ROOM_NO
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    public BigDecimal getRoomNo() {
        return roomNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSE.ROOM_NO
     *
     * @param roomNo the value for HOUSE.ROOM_NO
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    public void setRoomNo(BigDecimal roomNo) {
        this.roomNo = roomNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSE.FLOOR_SPACE
     *
     * @return the value of HOUSE.FLOOR_SPACE
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    public BigDecimal getFloorSpace() {
        return floorSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSE.FLOOR_SPACE
     *
     * @param floorSpace the value for HOUSE.FLOOR_SPACE
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    public void setFloorSpace(BigDecimal floorSpace) {
        this.floorSpace = floorSpace;
    }
}