package com.hky.wuyefeiguanli.dao;

import com.hky.wuyefeiguanli.model.DealList;
import com.hky.wuyefeiguanli.model.DealListExample;
import com.hky.wuyefeiguanli.model.DealListWithBLOBs;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DealListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    long countByExample(DealListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    int deleteByExample(DealListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    int deleteByPrimaryKey(BigDecimal dealId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    int insert(DealListWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    int insertSelective(DealListWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    List<DealListWithBLOBs> selectByExampleWithBLOBs(DealListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    List<DealList> selectByExample(DealListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    DealListWithBLOBs selectByPrimaryKey(BigDecimal dealId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    int updateByExampleSelective(@Param("record") DealListWithBLOBs record, @Param("example") DealListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") DealListWithBLOBs record, @Param("example") DealListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    int updateByExample(@Param("record") DealList record, @Param("example") DealListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    int updateByPrimaryKeySelective(DealListWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(DealListWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_LIST
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    int updateByPrimaryKey(DealList record);
}