package com.hky.wuyefeiguanli.dao;

import com.hky.wuyefeiguanli.model.HouseLinkman;
import com.hky.wuyefeiguanli.model.HouseLinkmanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HouseLinkmanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_LINKMAN
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    long countByExample(HouseLinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_LINKMAN
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    int deleteByExample(HouseLinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_LINKMAN
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    int insert(HouseLinkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_LINKMAN
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    int insertSelective(HouseLinkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_LINKMAN
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    List<HouseLinkman> selectByExample(HouseLinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_LINKMAN
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    int updateByExampleSelective(@Param("record") HouseLinkman record, @Param("example") HouseLinkmanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_LINKMAN
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    int updateByExample(@Param("record") HouseLinkman record, @Param("example") HouseLinkmanExample example);
}