package com.hky.wuyefeiguanli.dao;

import com.hky.wuyefeiguanli.model.HousePayment;
import com.hky.wuyefeiguanli.model.HousePaymentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HousePaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_PAYMENT
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    long countByExample(HousePaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_PAYMENT
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    int deleteByExample(HousePaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_PAYMENT
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    int insert(HousePayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_PAYMENT
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    int insertSelective(HousePayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_PAYMENT
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    List<HousePayment> selectByExample(HousePaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_PAYMENT
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    int updateByExampleSelective(@Param("record") HousePayment record, @Param("example") HousePaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_PAYMENT
     *
     * @mbg.generated Sun Aug 20 20:51:56 CST 2017
     */
    int updateByExample(@Param("record") HousePayment record, @Param("example") HousePaymentExample example);
}