package com.hky.wuyefeiguanli.dao;

import com.hky.wuyefeiguanli.model.House;
import com.hky.wuyefeiguanli.model.HouseExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    long countByExample(HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    int deleteByExample(HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    int deleteByPrimaryKey(BigDecimal houseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    int insert(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    int insertSelective(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    List<House> selectByExample(HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    House selectByPrimaryKey(BigDecimal houseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    int updateByExampleSelective(@Param("record") House record, @Param("example") HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    int updateByExample(@Param("record") House record, @Param("example") HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    int updateByPrimaryKeySelective(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE
     *
     * @mbg.generated Sun Aug 20 20:51:55 CST 2017
     */
    int updateByPrimaryKey(House record);
}