package com.hky.model;

public class A {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column A.A
     *
     * @mbg.generated Fri Aug 18 01:49:20 CST 2017
     */
    private String a;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column A.A
     *
     * @return the value of A.A
     *
     * @mbg.generated Fri Aug 18 01:49:20 CST 2017
     */
    public String getA() {
        return a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column A.A
     *
     * @param a the value for A.A
     *
     * @mbg.generated Fri Aug 18 01:49:20 CST 2017
     */
    public void setA(String a) {
        this.a = a;
    }
}